### ISSUE TITLE
Code for Seg-mAP

### ISSUE THREAD

**Issue by LannCX** [MCG-NJU/PointTAD#2]
Hi, thanks for sharing the solid code! 
Do you willing to release the evaluation code for Seg-mAP? I have reproduced the Det-mAP in your paper, but the Seg-mAP is much lower without the exact implementation of Gaussian kernel-based approximation.

**Comment by sparkstj** [comment]
Sorry for the late reply. The evaluation code for Seg-mAP on multithumos is uploaded [here](https://github.com/MCG-NJU/PointTAD/blob/main/multithumos_dense.ipynb), please check it out.

**Comment by LannCX** [comment]
Grateful for your timely update, and my issue is solved now.
